[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eccoseas"
authors = [{name = "Mike Wood", email = "mike.wood@sjsu.edu"}]
version = "0.1.0"
description = "A toolkit for ECCO and MITgcm regional models"
